<a href="https://colab.research.google.com/github/nisanurguney/bitirme_projesi_datalari/blob/main/bitirme_projesi_notebooku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bazı verilerde sayı türünde uyuşmazlıklar olduğu için python'da düzeltmeler yapılmıştır.

Hastane Yatak Sayılarının İllere Göre Dağılımı tablosunun düzeltilmesi

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving dosya1.csv to dosya1.csv

In [ ]:
df = pd.read_csv("dosya1.csv", encoding="utf-8")

In [ ]:
df.head()

  Province                          hospital_type  year  beds
0    Adana  Sağlık Bakanlığı - Ministry of Health  2020  4121
1    Adana  Sağlık Bakanlığı - Ministry of Health  2021  4176
2    Adana  Sağlık Bakanlığı - Ministry of Health  2022  4265
3    Adana  Sağlık Bakanlığı - Ministry of Health  2023  4510
4    Adana                Üniversite - University  2020  1747

In [ ]:
df.columns = ["province", "hospital_type", "year", "beds"]

In [ ]:
df["province"] = df["province"].astype(str)
df["hospital_type"] = df["hospital_type"].astype(str)

In [ ]:
df["beds"] = df["beds"].astype(str).str.replace(" ", "")
df["beds"] = df["beds"].astype(int)

In [ ]:
df["year"] = pd.to_datetime(df["year"], format="%Y").dt.year.astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   province       744 non-null    object
 1   hospital_type  744 non-null    object
 2   year           744 non-null    int64
 3   beds           744 non-null    int64
dtypes: int64(2), object(2)
memory usage: 23.4+ KB

In [ ]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2026.2.25)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from pandas_gbq import to_gbq

to_gbq(
    df,
    "bitirme_projesi_datalari.hastane_yatak_sayilarinin_illere_gore_dagilimi_clean_data",
    project_id="workintech-projelerim",
    if_exists="replace"
)

100%|██████████| 1/1 [00:00<00:00, 7530.17it/s]

Hekim sayısı, Hekim Başına Düşen Kişi Sayısı ve Hekim Başına Düşen Toplam Müracaat Sayısı tablosunun düzeltilmesi

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving dosya2.csv to dosya2 (1).csv

In [ ]:
df = pd.read_csv("dosya2.csv", encoding="utf-8")

In [ ]:
df.head()

   date physician_count  people_per_physician\n visits_per_physician
0  2015         141,259                     557                4 673
1  2016         144 827                     551                4 735
2  2017         149 997                     539                4 793
3  2018         153 128                     536                5 110
4  2019         160 810                     517                5 055

In [ ]:
df.columns = ["date", "physician_count", "people_per_physician", "visits_per_physician"]

In [ ]:
df["date"] = pd.to_datetime(df["date"], format="%Y").dt.year.astype(int)

In [ ]:
df["physician_count"] = df["physician_count"].astype(str).str.replace(",", "").str.replace(" ", "").astype(int)

df["people_per_physician"] = df["people_per_physician"].astype(str).str.replace(",", "").str.replace(" ", "").astype(int)

df["visits_per_physician"] = df["visits_per_physician"].astype(str).str.replace(",", "").str.replace(" ", "").astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  9 non-null      int64
 1   physician_count       9 non-null      int64
 2   people_per_physician  9 non-null      int64
 3   visits_per_physician  9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [ ]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2026.2.25)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
print(df.columns)

Index(['date', 'physician_count', 'people_per_physician',
       'visits_per_physician'],
      dtype='object')

In [ ]:
from pandas_gbq import to_gbq

to_gbq(
    df,
    "bitirme_projesi_datalari.hekim_sayilari_clean_data",
    project_id="workintech-projelerim",
    if_exists="replace"
)

100%|██████████| 1/1 [00:00<00:00, 883.57it/s]

İl Bazında Kişi Başına Gayri Safi Yurt İçi Hasıla tablosunun düzeltilmesi

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])
df.columns = df.columns.str.strip()

print(df.columns.tolist())

Saving dosya3.csv to dosya3.csv
['Unnamed: 0', '2020', '2021', '2022', '2023', '2024']

In [ ]:
df.rename(columns={df.columns[0]: "city"}, inplace=True)

In [ ]:
df_long = df.melt(
    id_vars="city",
    var_name="year",
    value_name="hasila"
)

In [ ]:
df_long["hasila"] = df_long["hasila"].astype(str).str.replace(" ", "").astype(int)

In [ ]:
print(df.columns.tolist())

['city', '2020', '2021', '2022', '2023', '2024']

In [ ]:
df_long = df.melt(
    id_vars="city",
    var_name="year",
    value_name="hasila"
)

In [ ]:
print(df_long.columns.tolist())

['city', 'year', 'hasila']

In [ ]:
df_long["hasila"] = (
    df_long["hasila"]
    .astype(str)
    .str.replace(" ", "", regex=False)
    .astype(int)
)

In [ ]:
df_long["year"] = df_long["year"].astype(int)

In [ ]:
df_long.info()
df_long.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405 entries, 0 to 404
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    405 non-null    object
 1   year    405 non-null    int64
 2   hasila  405 non-null    int64
dtypes: int64(2), object(1)
memory usage: 9.6+ KB

         city  year  hasila
0    İstanbul  2020   94296
1    Tekirdağ  2020   83932
2      Edirne  2020   53060
3  Kırklareli  2020   70329
4   Balıkesir  2020   53779

In [ ]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2026.2.25)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from pandas_gbq import to_gbq

to_gbq(
    df_long,
    "bitirme_projesi_datalari.gayri_safi_yurt_ici_hasila_clean_data",
    project_id="workintech-projelerim",
    if_exists="replace"
)

100%|██████████| 1/1 [00:00<00:00, 10538.45it/s]

Türkiye toplam sağlık sigortası poliçe sayısı tablosunun düzenlenmesi

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])
df.columns = df.columns.str.strip()

print(df.columns.tolist())

Saving dosya4.csv to dosya4.csv
['date', 'dual', 'health', 'illness']

In [ ]:
df.columns = df.columns.str.strip()

df["date"] = df["date"].astype(int)

cols = ["dual", "health", "illness"]

for col in cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(" ", "", regex=False)
        .str.replace(".", "", regex=False)
        .str.replace(",", "", regex=False)
        .astype(int)
    )

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     9 non-null      int64
 1   dual     9 non-null      int64
 2   health   9 non-null      int64
 3   illness  9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

   date     dual   health  illness
0  2015  3073694  1068854  2744330
1  2016  3331681  1353860  2800330
2  2017  4302549  1719974  2627300
3  2018  4361433  1882287  2165390
4  2019  6007999  2894597  2447180

In [ ]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2026.2.25)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from pandas_gbq import to_gbq

to_gbq(
    df,
    "bitirme_projesi_datalari.saglik_sigortasi_police_sayisi_clean_data",
    project_id="workintech-projelerim",
    if_exists="replace"
)

100%|██████████| 1/1 [00:00<00:00, 15534.46it/s]

Yıllara Göre İl Nufüsları Tablosunun düzeltilmesi

In [ ]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/1xOACw3R58DHsmUXloQ411FE1x4HjgARcgaPuhZaVmY4/export?format=csv"

df = pd.read_csv(url)

df.columns = ["city", "year", "population"]

df["year"] = df["year"].astype(int)
df["population"] = df["population"].astype(int)

df = df.dropna()

df.head()

    city  year  population
0  Adana  2020     2258718
1  Adana  2021     2263373
2  Adana  2022     2274106
3  Adana  2023     2270298
4  Adana  2024     2280484

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        486 non-null    object
 1   year        486 non-null    int64
 2   population  486 non-null    int64
dtypes: int64(2), object(1)
memory usage: 11.5+ KB

    city  year  population
0  Adana  2020     2258718
1  Adana  2021     2263373
2  Adana  2022     2274106
3  Adana  2023     2270298
4  Adana  2024     2280484

In [ ]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.0)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.3.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.40.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.8.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2026.2.25)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
from pandas_gbq import to_gbq

to_gbq(
    df,
    "bitirme_projesi_datalari.nufus_sayisi_clean_data",
    project_id="workintech-projelerim",
    if_exists="replace"
)

100%|██████████| 1/1 [00:00<00:00, 15420.24it/s]